### ISSUE TITLE
Missing `roundRect` method

### ISSUE THREAD

**Issue by CreativeTechGuy** [nilzona/path2d-polyfill#41]
There is a somewhat new method [roundRect](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect) which this polyfill doesn't support currently.

For context, I'm using this in [JSDOM](https://github.com/jsdom/jsdom) with [node-canvas](https://github.com/Automattic/node-canvas) since they [don't have an implementation for the Path2D methods](https://github.com/Automattic/node-canvas/issues/1116) out of the box.

**Comment by nilzona** [comment]
hey @CreativeTechGuy thank you.

out of curiosity, how do you use this polyfill in a node environment?

**Comment by CreativeTechGuy** [comment]
I'm not sure what you mean by "how". I'm writing Jest tests for canvas applications that use Path2D methods which aren't implemented so this is the only library I found which has an implementation that works enough to produce reasonably accurate test results.

**Comment by nilzona** [comment]
right .. @CreativeTechGuy  .. I was just curious how you use this library in a node environment since it's written for browsers and add things to the global window object. But I guess since the polyfill function accepts the window as a function parameter you could just pass in a "window-like" object into the function.

**Comment by CreativeTechGuy** [comment]
Yeah that's where Jest and JSDOM comes in. It simulates all of the browser globals and the DOM, plus node-canvas implements most of the canvas methods.

**Comment by nilzona** [comment]
@CreativeTechGuy would you like to try out the beta version `path2d-polyfill@2.0.0-beta.0` ?

a code example of how to use it can be found here https://gist.github.com/nilzona/e611c99336d8ea1f645bd391a459c24f

**Comment by CreativeTechGuy** [comment]
Sorry for the late reply. I tried it out. It doesn't work smoothly for JSDOM/Jest test usage, but that's unrelated to this issue. (I needed to make small edits before to get it to work and I need to make less edits now, so an improvement!)

I like the improvements to the bundling!

I'm curious why `polyfillRoundRect` needs to be a separate method though and not part of `polyfillPath2D`? It seems like you'd need to call `polyfillPath2D(window); polyfillRoundRect(window);` for it to be fully polyfilled now?

----

And although unrelated, if you are curious, JSDOM with Canvas doesn't have `window.CanvasRenderingContext2D`. It does exist, just not on the global object. To get it to work previously, I had to do:

```
const canvasElement = document.createElement("canvas");
const contextInstance = canvasElement.getContext("2d");
const CanvasRenderingContext2DPrototype = Object.getPrototypeOf(contextInstance);
```
And then I'd replace instances of `CanvasRenderingContext2D.prototype` with `CanvasRenderingContext2DPrototype`.

**Comment by nilzona** [comment]
ok thank you @CreativeTechGuy  .. so is that the only way you get hold of the prototype object for CanvasRenderingContext2D in a JSDOM environnment?

**Comment by CreativeTechGuy** [comment]
So it's a bit weird. Here's the situation. JSDOM doesn't support canvas out of the box. But it does check for another library [canvas](https://www.npmjs.com/package/canvas) and if that library is present, then it'll set it up as the implementation. So on it's own JSDOM has nothing canvas related. Now the `canvas` library does have a `CanvasRenderingContext2D` which it exports, but it's not assigned to any global object.

I could do something like this:

```
import { CanvasRenderingContext2D } from "canvas";

global.CanvasRenderingContext2D = CanvasRenderingContext2D;
polyfillPath2D(global);
```

That actually works well and doesn't require any modifications of your polyfill. So I'll start using that going forward. Maybe that could be documented in this library somewhere?

**Comment by nilzona** [comment]
@CreativeTechGuy  .. that's great, thank you
