### ISSUE TITLE
default import has no exports

### ISSUE THREAD

**Issue by CreativeTechGuy** [nilzona/path2d-polyfill#45]
A few related problems:

The obvious import doesn't have any exports:

```
import { polyfillPath2D } from "path2d-polyfill";
```

If this resolves to the `exports.default` or `browser` file, both of those are `.min.js` which don't have any exports so this code will break.

The docs mention:

```
const { polyfillPath2D } = require("path2d-polyfill/path2d");
```

But this path doesn't exist so that doesn't work.

-----

Running unit tests with Jest in Node uses the `exports.default` export so that breaks. I've never published a package which uses the `browser` field, but I assume that can stay the same, as long as all of the other exports offer the same exports so bundlers and other tools don't crash when importing.

**Comment by nilzona** [comment]
> const { polyfillPath2D } = require("path2d-polyfill/path2d");

This is a typo and will be fixed.

> import { polyfillPath2D } from "path2d-polyfill"; 

Is this typescript? .. I am running this code in .esm and it works fine.

**Comment by CreativeTechGuy** [comment]
Yes I'm using TypeScript, but not compiling with TypeScript. The lack of types is a separate issue (#44) but at runtime I set a breakpoint in the debugger in Node and don't see any properties on the object.

I suspect if you are running this in Node and aren't seeing an issue, then it's Jest's module resolution which seems to pick up the `path2d-polyfill.min.js` file (which is referenced as the "default" export in your `package.json`)

**Comment by nilzona** [comment]
Yes I am using node ..  when using jest and jest-dom there might be other resolution methods compared to node ... (even if it is node). I'll look into it.

Maybe the `exports` fields just messes things up.  `main` and `browser` should be enough for most use cases.

**Comment by nilzona** [comment]
another approach could be to release two different packages. `path2d` (use in node/jest)  and `path2d-polyfill` (only for browser). 

`path2d-polyfill` would basically just grab `path2d` and "browserify" it.

**Comment by CreativeTechGuy** [comment]
Not sure if it's helpful, but at least in my case, simply removing the whole `exports` section from `package.json` fixed my issue. But really that's just saying that the `path2d-node.cjs` export works for me so not super revolutionary.

Maybe a single UMD export would make it simpler?

**Comment by nilzona** [comment]
The thing is that `path2d-polyfill.js` is fundamentally different from `path2d-node.cjs`  the pollyfill does not export anything but it runs the polyfill functions on the window object, which is what you want in a browser environment.

The `path2d-node.cjs` does not self-execute anything, but it exports all the needed polyfill functions along with Path2D so that you can pass in a "global" object with CanvasRenderingContext2D attached to it.

That's why I think it might be better off with two separate libraries ..

**Comment by CreativeTechGuy** [comment]
Got it. Makes sense!

**Comment by LinusU** [comment]
> another approach could be to release two different packages. `path2d` (use in node/jest) and `path2d-polyfill` (only for browser).
> 
> `path2d-polyfill` would basically just grab `path2d` and "browserify" it.

I think that this would be great!

My use case is using this in the node canvas package, and depending directly on just `path2d` that doesn't have any browser stuff would be great!

**Comment by nilzona** [comment]
yeah .. the browser library would only be for IE11 basically.

**Comment by CreativeTechGuy** [comment]
Would it be better long term to merge this Path2D code into [node-canvas](https://github.com/Automattic/node-canvas) and then this can be kept around for anyone who still needs a polyfill? That way you wouldn't need to be the sole maintainer of this anymore and the community could help maintain it for the future.

**Comment by nilzona** [comment]
> yeah .. the browser library would only be for IE11 basically.

except the RoundRect functions ...  Firefox does not have support for that, this polyfill fixes it though.

**Comment by vixalien** [comment]
I think it would be a good idea to provide the `Path2D` class on it's own (if it's already done, it would be nice if it was in the README) since for some people (like me) not messing with `global` is important.

One could just `import { Path2D }` and the global instance would be alright

**Comment by nilzona** [comment]
This repo is now releasing a `path2d` node library
